modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="astralvoyage"
version="0.1.0"
displayName="Astral Voyage"
credits=""
authors="mistersecret312, Povstalec"
displayTest="MATCH_VERSION"

description='''Space Travel'''
[[dependencies.astralvoyage]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.astralvoyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"